language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    packages:
    - libasound2-dev
    - librtlsdr-dev
matrix:
  allow_failures: nightly
before_install:
  - |
    wget https://github.com/zeromq/zeromq4-1/archive/v4.1.6.tar.gz
    tar zxf v4.1.6.tar.gz
    cd zeromq4-1-4.1.6
    ./autogen.sh
    ./configure --prefix=$HOME
    make
    make install
    cd ..
script:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all --features=zmq_node
  - cargo build --release --example bpsk_mod
  - cargo build --release --example single_thread_bpsk
  - cargo build --release --example fm_radio --features="rtlsdr_node audio_node"
  - cargo build --release --example play_audio --features="audio_node"
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - LD_LIBRARY_PATH=$HOME/lib
  - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
