language: rust
sudo: false
rust:
  - stable
  - beta
addons:
  apt:
    packages:
    - libasound2-dev
    - librtlsdr-dev
before_install:
  - |
    wget https://github.com/zeromq/zeromq4-1/archive/v4.1.6.tar.gz
    tar zxf v4.1.6.tar.gz
    cd zeromq4-1-4.1.6
    ./autogen.sh
    ./configure --prefix=$HOME
    make
    make install
    cd ..
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy --all --examples
  - cargo build --verbose --all
  - cargo test --verbose --all --features=zmq_node
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
  - LD_LIBRARY_PATH=$HOME/lib
  - PKG_CONFIG_PATH=$HOME/lib/pkgconfig
